Adding SAI Challenger with DASH enhancements and test cases
Azure/DASH pull request #259
Opened 2022-10-19 06:15 UTC by chrispsommers

1. Introduced a new way to develop tests - DASH-like test configuration used for both DUT and traffic generator.
2. Added scalable test examples for VNET2VNET use case with SAI configuration generation using “saigen” module.
3. Added OTG/snappi helper modules to scale traffic profile.
4. Added SAI-Challenger submodule and testbed definitions (definition only, testbed itself stays without changes)
5. Extended existing dash-saithrift-client with SAI-Challenger client modules and confgen requirements.
6. Enabled new test cases on CI
7. Documentation

2022-10-19 06:24 UTC, lguohan commented on .gitmodules
> +	url = https://github.com/opencomputeproject/SAI-Challenger
not sure we can support sai challenger for dash project.

2022-10-19 06:24 UTC, lguohan requested changes
need to have discussion on introducing sai challenger to the test repo.

2022-10-19 06:29 UTC, chrispsommers commented
> need to have discussion on introducing sai challenger to the test repo.

Plenty of time to discuss, this is a draft PR and the presentation to the community is to be resumed shortly. Thanks.

2022-11-02 15:52 UTC, lguohan commented on .gitmodules
> +	url = https://github.com/mgheorghe/cgyang
why personal repo?

2022-11-07 20:52 UTC, chrispsommers commented
Replaced by https://github.com/Azure/DASH/pull/278

2022-11-07 20:52 UTC, closed without merging