Standardize DASH tests location.
Azure/DASH pull request #277
Opened 2022-11-06 11:43 UTC by aputriax

- Moved all existing tests under test/test-cases
- Updated docker files to add/mount new location
- Updated documentation.

Signed-off-by: Anton Putria <antonx.putria@intel.com>

2022-11-06 11:50 UTC, aputriax commented
@chrispsommers @mhanif I merged and moved your tests to test/test-cases/functional/saidashvnet_experimental.py

This branch is still WIP.

@chrispsommers I need your advise what to do with pytest folder. It seems that we need to move it to test/test-cases/functional as well. Should it be test/test-cases/pytest? Any thoughts?

2022-11-07 18:57 UTC, chrispsommers commented on dash-pipeline/Makefile
> +	./run-functional-tests.sh
We could continue to run tests in both locations in perpetuity. dash-pipeline tests could continue to be developed in incubation mode, let's discuss in community.

2022-11-07 19:01 UTC, chrispsommers commented
Hi Anton, As we discussed, the idea here (which I support) is to routinely "promote" tests from dash-pipeline/tests to /tests and use this location for stable production tests, and relegate dash-pipeline/tests for incubating tests. This should be presented to the community for buy-in and education.

Regarding moving some tests to test/test-cases/functional/saidashvnet_experimental.py, it should be done in one PR, i.e. I don't like the idea of deleting them in this PR, and thereby losing the CI testing until a later PR restores them elsewhere.

2022-11-09 17:31 UTC, aputriax commented on test/test-cases/functional/saidashvnet_experimental.py
> +from sai_thrift.sai_headers import *
Rename the file to saidashvnet_basic.py

2022-11-16 17:54 UTC, chrispsommers commented
@vmytnykx @aputriax Please submit a PR to https://github.com/Azure/DASH/tree/PR277-staging-branch. Make sure you've updated the dockerfile tags. I can accept the PR and it will publish the new dockerfile. Then you can submit the PR to main and it should succeed in CI because the dockerfile will be available for pulling.

2022-11-29 15:33 UTC, chrispsommers approved these changes

2022-11-29 17:18 UTC, chrispsommers commented on test/test-cases/functional/README.md
> +| [`saidashvnet_experimental.py`](./functional/ptf/saidashvnet_experimental.py) | Basic positive VNET-to-VNET test cases designed for running on BMv2
I think you now have saidashvnet.py and saidashvnet_sanity.py - need to update table?

2022-11-29 17:20 UTC, chrispsommers commented on test/test-cases/scale/README.md
> +| [vnet2vnet](scale/vnet2vnet/README.md) | Scale DASH vnet2vnet Tests
link broken - remove `scale` from path

2022-11-29 17:28 UTC, chrispsommers requested changes
Please fix tables and links in the READMEs, otherwise LGTM.

2022-11-29 18:48 UTC, chrispsommers approved these changes

2022-12-02 17:27 UTC, lguohan approved these changes

2022-12-02 17:27 UTC, merged